### ISSUE TITLE
Failure in Concurrency mode with workerOptions mode 'module'

### ISSUE THREAD

**Issue by robertomonno77** [johnny-quesada-developer/easy-web-worker#10]
If I try to run multiple operations using a web-worker created in 'module' mode, I receive an error in the web console:
"> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec."

I do *not* receive any errors and the web-worker successfully complete using only 1 operation. That is quite strange!

Basically, this is pseudo-code example:
- main
`
const results = await Promise.all([
   worker.send(msg1),
   worker.send(msg2), /* if I comment out this line all seem to work fine! */
]);
`
- workerFactory
`
return createEasyWebWorker(
   new Worker(new URL('my-static-worker-file', import.meta.url)),
        {
	   workerOptions: { type: 'module' },
           maxWorkers: 4,
	},
)
`

It seems to me something related to the web-workers creation.... Do you please point me to the right way to proceed ?
Thanks for your support & great work in this library!

**Comment by robertomonno77** [comment]
Maybe it is only something to be explain much more better in the documentation but using this minor change in my code it is running without errors....

`
return createEasyWebWorker(
		[
			new Worker(new URL('./EasyColorsEvaluationWorker.js', import.meta.url)),
		],
....
`

The first parameter is now a Worker list of 1 element.... :-)

**Comment by johnny-quesada-developer** [comment]
Hi @robertomonno77,

Thank you very much for trying out the package and sharing your experience! I apologize for the delayed response.

Implementing workers can indeed be tricky, especially with the various ways you can import the worker source. I’m glad you managed to identify the issue and find a solution.

I completely agree that more examples in the documentation could have mitigated this confusion. I've added your example, as well as another one specifically for Vite and TypeScript, which is a common setup these days.

Your feedback is incredibly valuable, and I truly appreciate your contribution! Please continue using the library, and feel free to reach out if you'd like to collaborate further—whether it's updating the documentation or extending the capabilities of easy-web-worker.

Thank you again for your support and for helping to improve this project!

Best regards,
Johnny Quesada
<img width="844" alt="image" src="https://github.com/user-attachments/assets/6f884a05-e2a5-4ca4-a58a-7bdc4a59a151">
