### ISSUE TITLE
Errors with angular

### ISSUE THREAD

**Issue by xbauquet** [johnny-quesada-developer/easy-web-worker#3]
Hi,

Thank you for this library, it looks really convenient, but I cannot seem to make it work with angular.
I made a minimal example to reproduce the problem I'm having:

https://github.com/xbauquet/angular-easy-web-worker

Just run `ng serve` after your `npm install` and you should see the errors.

I'm not sure to understand what's happening but to me it looks like a conflict between the lib worker and the lib dom.
Here is a little part of the errors (there's to many to past here):

```
Error: node_modules/typescript/lib/lib.webworker.d.ts:6051:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'onunhandledrejection' must be of type '((this: Window, ev: PromiseRejectionEvent) => any) | null', but here has type '((this: DedicatedWorkerGlobalScope, ev: PromiseRejectionEvent) => any) | null'.

6051 declare var onunhandledrejection: ((this: DedicatedWorkerGlobalScope, ev: PromiseRejectionEvent) => any) | null;
                 ~~~~~~~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:18264:13
    18264 declare var onunhandledrejection: ((this: Window, ev: PromiseRejectionEvent) => any) | null;
                      ~~~~~~~~~~~~~~~~~~~~
    'onunhandledrejection' was also declared here.


Error: node_modules/typescript/lib/lib.webworker.d.ts:6053:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'self' must be of type 'Window & typeof globalThis', but here has type 'WorkerGlobalScope & typeof globalThis'.

6053 declare var self: WorkerGlobalScope & typeof globalThis;
                 ~~~~

  node_modules/typescript/lib/lib.dom.d.ts:17912:13
    17912 declare var self: Window & typeof globalThis;
                      ~~~~
    'self' was also declared here.
```

I would really appreciate any help you can give me.

**Comment by xbauquet** [comment]
It looks like adding `"skipLibCheck": true` to the `tsconfig.json` remove these errors, but it's a little bit annoying to loose lib check. Any other solution / idea ?

**Comment by johnny-quesada-developer** [comment]
Hi @xbauquet ,

I added the dependency **webworker** to **typescript** that should solve the issue, please let me know if it works for you.

Regards
