### ISSUE TITLE
Suggest not using `substr` and `new Date`

### ISSUE THREAD

**Issue by gabrielecirulli** [johnny-quesada-developer/easy-web-worker#4]
Within the following line, I would suggest replacing the `Date` allocation with a call to `Date.now()` and the use of `substr` (which is deprecated) with the equivalent `substring`

https://github.com/johnny-quesada-developer/easy-web-worker/blob/6c9b2317c18652c38bcfbf4a8f2d6489b80b677b/src/EasyWebWorkerFixtures.ts#L2

**Comment by johnny-quesada-developer** [comment]
Hi @gabrielecirulli, you are absolutely right! **substr** has been marked as legacy, so I am more than happy to implement your suggestion in version 4.0.3.

Thank you so much for taking the time to review it and, hopefully, for giving the package a try.

I haven't prepared a contribution readme yet, but I will do so soon. In the meantime, please feel welcome to share any ideas or collaborations that could improve this package and help it reach more people.

Regards, and again, thank you so much.

**Comment by johnny-quesada-developer** [comment]
suggestion was implemented and published in version 4.0.3
