### ISSUE TITLE
How to send a message from inside a static worker to the main thread without having received a message first?

### ISSUE THREAD

**Issue by gabrielecirulli** [johnny-quesada-developer/easy-web-worker#9]
I'm a bit stumped on this one. I have a `worker.ts` script which contains the code that runs in a Web Worker. Sometimes, I want to send messages from the Worker to the main thread, without having received a message from the main thread (i.e. not in response to an existing message).

I cannot find a way to do this. In my worker I create a `StaticEasyWebWorker` like so:
```ts
const easyWorker = new StaticEasyWebWorker<WorkerMessage, WorkerResponse>();
```

However on `easyWorker` there is no method to send.

Do you have any suggestions?

**Comment by gabrielecirulli** [comment]
To add detail to my request, I want to enable two-way communication between my worker and the main thread, allowing the worker to initiate sending messages and receive responses from the main thread. This should closely resemble the existing communication setup initiated by the main thread.

**Comment by johnny-quesada-developer** [comment]
Hi @gabrielecirulli,

I'm sorry for the late response. Currently, easy-worker does not support messages with cancelable promises from inside the worker to the main thread.

Even so, let's try to solve this:

The first thing you're going to need is to use the parameter: "keepAlive", so the worker will be initialized immediately without the need for messages.

Then:

*   You can access the worker directly, so if no other configuration was added, there should be just one worker in the workers array.

```tsx
const [worker] = easyWorker.workers;
```

Once you have the worker instance, you can wrap the default message handler and add whatever you need.

```tsx
const { onMessage: onMessageBase } = worker;  

worker.onMessage = (event: MessageEvent<IMessageData<TPayload>>) => {    
  const { someFlag } = event.data;
  
  if (!someFlag) return onMessageBase(event);
  
  // your custom handler. 
  
}
```

This option basically allows you to unblock whatever you need.

Another option that came to my mind is related to the fact that the messages do not expire. So, if you have just one process that eventually is going to resolve from inside the worker to the main thread, you can cache the first message inside the worker and resolve it once all the necessary conditions are met.

```tsx
const worker = createEasyWorker();  

worker.send().then(() => {     
   // this promise will be alive as long as the worker is alive, so it can be resolved at any moment from inside the worker
});
```

Another option, depending on what you need, is to use the `reportProgress` method. So, again, having an open message, and from inside the worker, you can actually report as many times as you wish to the `onProgress` callback in the main thread. Example:

```tsx
const worker = createEasyWorker();

worker.send().onProgress(() => {
    // this callback could be executed as many times as you wish from inside the worker as long as the message is not resolved

    // executes as many times as you want
}).then(() => {
  // executes just once
});

// Inside the worker:

const payload = {} // whatever you need

// this can be called multiple times
openMessage.reportProgress(0, payload, transferables);

```

I hope these options help in addressing your concerns.

**Comment by gabrielecirulli** [comment]
Thank you for your response! In the end I wrote my own library, with two way fully typed RPC with promises (the only difference is they're not cancelable, I still haven't figured out the use case for that) and I also added event emitters and listeners as a bonus. I haven't open sourced it, I may do so later on.
